name: Deploy Stack to Raspberry Pi

on:
  push:
    branches: [ "master" ] # Triggers only when code hits the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Raspberry Pi

    steps:
      # 1. Pull down your repository code into the GitHub runner
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Open an SSH connection to your Pi, sync the project folder, and rebuild
      - name: Deploy to Pi via SSH
        uses: appleboy/ssh-action@v1.0.3
        env: # 2. Hands off the unlocked secrets to this specific step
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD }}
          SERVER_PORT: ${{secrets.SERVER_PORT}}
          TIME_ZONE: ${{ secrets.TIME_ZONE }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22 # Change this if your SSH runs on a non-standard port
          envs: MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD, TIME_ZONE, GOOGLE_API_KEY, MYSQL_PORT, SERVER_PORT
          debug: true
          script: |
            set -ex 
            # 1. Navigate to your project directory (or create it if it doesn't exist)
            cd ~/app_root/activeto_api/Active_Toronto_Docker
            
            # 2. Pull the latest code straight from GitHub
            git pull origin master
            
            echo "MYSQL_DATABASE=$MYSQL_DATABASE" > .env
            echo "MYSQL_USER=$MYSQL_USER" >> .env
            echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
            echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" >> .env
            echo "MYSQL_PORT=$MYSQL_PORT" >> .env
            echo "SERVER_PORT=$SERVER_PORT" >> .env
            echo "TIME_ZONE=$TIME_ZONE" >> .env
            echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
            
            # 3. Pull down any updated base images, rebuild, and launch detached
            docker compose pull
            docker compose up -d --build
            
            # 4. Clean up old dangling images to save precious Raspberry Pi storage
            docker image prune -f
